### ISSUE TITLE
Serialisers

### ISSUE THREAD

**Issue by rawkode** [spreedly/kaffe#33]
I seem to be implementing the same functions in most of my services, that is:

```elixir
def handle_message(message = %{}) do
  message[:value]
  |> Poison.decode!(as: %Event{})
  |> handle_message!()
end
```

I was thinking I would take a stab at implementing the following, should you consider it applicable to generic-use and would accept the PR:

```elixir
config :kaffe, serialiser: CustomSerialiser # Must implement Kaffe.SerialiserBehaviour?
```
Then, when configured, would deserialise the message and then call `handle_message/2`

This would allow serialisers for protobufs, thrift, messagepack, etc.

**Comment by rwdaigle** [comment]
Hi @rawkode, thanks for this suggestion!

I generally try to avoid adding pluggable functionality to do something that's already easily accessible. So in this case the value of a config-specified serializer seems low since it's not hard for implementers to know how or where to implement that functionality themselves (right there in the message handler!). Doing otherwise tends to just increase the framework's surface area for little real value. But that's purely from a feature management perspective. Perhaps there's value in having a few common serializer implementations already available?

Happy to hear others' thoughts!

/cc @sdball @objectuser

**Comment by rawkode** [comment]
@rwdaigle I'm now running 9 different services, all implementing the same piece of functionality. Perhaps I am in a minority with my usage. Although the setup is trivial, I do prefer not repeating myself :smile:

**Comment by sdball** [comment]
How about making your serializer logic into its own dependency via mix to be called from each `handle_message`?

```elixir
def handle_message(message) do
  MyCustomMessageParser.parse!(message)
  |> other_things
  |> for_this_service
end
```

You'd still get consolidated parsing logic with minimal supporting code. But instead of one line of configuration you'd have one line of message handling code. That keeps Kaffe's contract simpler and keeps all the message handling logic out in the open.

**Comment by rawkode** [comment]
OK. I'm sensing you aren't keen on this idea :joy: 

I'll close it and work around it.

**Comment by rwdaigle** [comment]
Haha, sorry @rawkode!

I think this is a great use-case that forces us to be more explicit about the contract for Kaffe. In my mind it's a low-level Kafka library that handles much of the nuance associated with practical usage of Kafka. So one-level above a pure adapter (that's what brod is), but not itself a framework. It's more of a convenience library.

I think a good litmus test for this is that I don't ever see Kaffe concerning itself with actual message bodies (parsing, plucking values, etc...), as that starts to get into domain logic. Anything Kafka metadata related however, I would see as fair game.

Hopefully that sounds logical vs. just an arbitrary line that you happen to be on the other side of for this example?

**Comment by rubberduck203** [comment]
Unfortunately, that’s an unexpected approach for the Kafka community. The JVM libs and the `librdkafka` family all expect producers/consumers to specify the serializer/deserializer as part of the config.

**Comment by sdball** [comment]
Kaffe was designed to make its use and setup as trivial as possible. In this it’s more like ruby-kafka’s approach to serialization: https://github.com/zendesk/ruby-kafka/blob/master/README.md#serialization
