### ISSUE TITLE
Producer: topics key required in configuration

### ISSUE THREAD

**Issue by scrogson** [spreedly/kaffe#73]
While working with Kaffe on a feature at work, I became very curious why the `topics` key was required for a producer. Given that Kaffe does not support dynamically creating Kafka topics, I began to wonder why it would be required at all.

Looking at the source I found this: https://github.com/spreedly/kaffe/blob/master/lib/kaffe/producer.ex#L76

Why is `topics` a list, and not a `topic` string?

I wondered what would happen if I just left it out completely (since I was not using `produce_sync/2`), and I got an error:

```
** (KeyError) key :topics not found in: [...]
```

Setting the `topics` key to `[]` seems to at least allow the app to boot, but it feels a bit odd.

Given that a producer can produce to any topic, it makes a bit more sense to me that those topics should be maintained in user-land code and passed into all `produce_sync/n` functions.

The reason I created this issue is to see if the maintainers might consider removing this requirement and `produce_sync/2` all together? I see little value in Kaffe implicitly choosing the first in a list of configured topics.

Am I missing something else that this `topics` list does?

**Comment by davidsantoso** [comment]
Makes sense. I believe the implicitness of `produce_sync/2` it's a bit of an artifact of how we push producer topics to configuration. It's a convenience function we made that's slightly tailored to our setup and certainly doesn't make sense for everyone. Certainly something we will consider as we continue to work on Kaffe but given our current work load, I'm not sure I can say when we may get to it.

However I'll make note of it in the README since it is quite implicit.

**Comment by objectuser** [comment]
@scrogson I've never thought it made sense and so as I've added new `produce_sync/*` functions, I've made them explicit. But that whole area needs some refactoring. I think if you look at past issues/PRs you can see some debate on how to move forward on those.

I think one of the "opinions" in Kaffe is that you'll be consuming and that's where the `:topics` list makes more sense.

**Comment by fatcatt316** [comment]
Closing due to above PR
